

apiVersion: chaos.galah-monitoring.io/v1
kind: TestRun
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pluck
  name: testrun-sample
spec: null
---
apiVersion: chaos.galah-monitoring.io/v1
kind: TestRunJob
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pluck
  name: testrunjob-sample
spec:
  args: ""
  env: null
  envConfigMap: ""
  jobTemplate:
    annotations:
      goodbye: hello
    labels:
      hello: goodbye
  schedule:
    minute: '*/15'
  scriptConfigMap: ""
  serviceAccount: k6-galah-testbed
  startingDeadlineSeconds: 60
  testName: k6-test
