---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-chaos-galah-monitoring-io-v1-testrunjob
  failurePolicy: Fail
  name: mtestrunjob.kb.io
  rules:
  - apiGroups:
    - chaos.galah-monitoring.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - testrunjobs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-chaos-galah-monitoring-io-v1-testrunjob
  failurePolicy: Fail
  name: vtestrunjob.kb.io
  rules:
  - apiGroups:
    - chaos.galah-monitoring.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - testrunjobs
  sideEffects: None
