---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - chaos.galah-monitoring.io
  resources:
  - testrunjobs
  - testruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chaos.galah-monitoring.io
  resources:
  - testrunjobs/finalizers
  - testruns/finalizers
  verbs:
  - update
- apiGroups:
  - chaos.galah-monitoring.io
  resources:
  - testrunjobs/status
  - testruns/status
  verbs:
  - get
  - patch
  - update
